SHOW DATABASES;
CREATE DATABASE customer_shopping_behavior;
use customer_shopping_behavior;
SELECT * FROM customers;

-- Q1 what is the total revenue generated by male vs Female Customer?
select gender, sum(purchase_amount) as total_revenue
from customers
group by gender;

-- Q2 Which customer used a discount but still spend more than the average purchase amount?
select customer_id,purchase_amount
from customers 
where discount_applied = "Yes" and purchase_amount > (select avg(purchase_amount) from customers);

-- Q3. Which are the top 5 products with the highest average review rating? 
select item_purchased , avg(review_rating) as avg_review_rating
from customers
group by item_purchased
order by avg_review_rating  desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,avg(purchase_amount) as avg_purchase_amount
from customers
where shipping_type in ("Standard","Express")
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status, 
count(customer_id) as total_customer,
avg(purchase_amount) as avg_purchase_amount,
sum(purchase_amount) as total_revenue 
from customers
group by subscription_status
order by total_revenue, avg_purchase_amount;


-- 06. Which.5 products have the highest percentage of purchases with discounts applied? (
select item_purchased, 
round(sum(case when discount_applied = "Yes" then 1 else 0 end) / count(*) * 100.0 , 2) as discount_rate
from customers
group by item_purchased
order by discount_rate desc
limit 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their  total number of previous purchases, and show the count of each segment.
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customers)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;
 
-- Q8. What are the top 3 most purchased products within each category? 
with item_counts as(
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over (
partition by category order by count(customer_id) desc) as item_rank
from customers
group by category,item_purchased)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select * from customers;
select  subscription_status, count(customer_id) as repeat_buyers
from customers
where previous_purchases > 5
group by subscription_status;

 -- Q10. What is the revenue contribution of each age group?
 select sum(purchase_amount) as total_revenue , age_group
 from customers
 group by age_group
 order by total_revenue desc;
 
